"""FastAPI application for the VBOGS Web Experiment Console."""

from __future__ import annotations

import asyncio
from contextvars import ContextVar
import json
import os
import re
import shlex
import subprocess
import uuid
from pathlib import Path
from typing import Any, AsyncIterator

import yaml
from fastapi import Request

from vbogs.dataset_inventory import clips_to_json, list_dataset_clips
from vbogs.web.config import ConfigValidationError, load_presets, resolve_config
from vbogs.web.scheduler import Scheduler, subprocess_runner
from vbogs.web.store import RunStore, TERMINAL_STATUSES, utc_now


STAGES = (
    "dynamic-mask", "prepare", "train", "stereo", "bucket", "fit", "inspect",
    "uncertainty", "map-viz", "render", "nbv", "nbv-viz", "bundle",
)
PROXY_USER: ContextVar[str | None] = ContextVar("vbogs_proxy_user", default=None)


class WebError(ValueError):
    pass


def repo_root() -> Path:
    return Path(__file__).resolve().parents[2]


def gpu_ids() -> tuple[str, ...]:
    values = tuple(item.strip() for item in os.environ.get("VBOGS_GUI_GPU_IDS", "0").split(",") if item.strip())
    if not values or any(not value.isdigit() for value in values) or len(set(values)) != len(values):
        raise RuntimeError("VBOGS_GUI_GPU_IDS must be a comma-separated unique list of GPU indexes")
    return values


def roles_for(user: str) -> set[str]:
    admins = {item.strip() for item in os.environ.get("VBOGS_GUI_ADMINS", "").split(",") if item.strip()}
    viewers = {item.strip() for item in os.environ.get("VBOGS_GUI_VIEWERS", "").split(",") if item.strip()}
    if user in admins:
        return {"viewer", "operator", "admin"}
    if not viewers or user in viewers:
        return {"viewer", "operator"}
    return {"viewer"}


def require_role(identity: dict[str, Any], role: str) -> None:
    if role not in identity["roles"]:
        raise PermissionError(f"The {role} role is required")


def stage_preconditions(run: dict[str, Any], start_at: str) -> list[Path]:
    root = Path(run["workspace_path"]) / "artifacts"
    scene = run["scene_id"]
    required: dict[str, list[Path]] = {
        "prepare": [],
        "train": [root / "colmap" / scene / "metadata.json"],
        "stereo": [root / "colmap" / scene / "metadata.json"],
        "bucket": [root / "points_world" / scene / "points_world.npz"],
        "fit": [root / "m4" / scene / "pts_by_anchor.npz"],
        "inspect": [root / "m4" / scene / "anchor_posterior.npz"],
        "uncertainty": [root / "m4" / scene / "anchor_posterior.npz"],
        "map-viz": [root / "m4" / scene / "U.npy"],
        "render": [root / "m4" / scene / "U.npy"],
        "nbv": [root / "m4" / scene / "U.npy"],
        "nbv-viz": [Path(run["output_path"]) / scene / "nbv" / "nbv_scores.json"],
        "bundle": [root / "m4" / scene / "U.npy"],
    }
    return required.get(start_at, [])


def _read_manifest(run: dict[str, Any]) -> dict[str, Any]:
    path = Path(run["output_path"]) / run["scene_id"] / "run_manifest.json"
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}
    return value if isinstance(value, dict) else {}


def _artifact_index(run: dict[str, Any], limit: int = 250) -> list[str]:
    root = (Path(run["output_path"]) / run["scene_id"]).resolve()
    if not root.is_dir():
        return []
    files: list[str] = []
    for path in sorted(root.rglob("*")):
        if path.is_file():
            files.append(path.relative_to(root).as_posix())
            if len(files) >= limit:
                break
    return files


def _render_container() -> str:
    project = os.environ.get("VBOGS_COMPOSE_PROJECT", "")
    filters = ["--filter", "label=com.docker.compose.service=vbogs-vbgs-render", "--filter", "status=running"]
    if project:
        filters.extend(["--filter", f"label=com.docker.compose.project={project}"])
    result = subprocess.run(["docker", "ps", "-q", *filters], check=True, capture_output=True, text=True)
    ids = [value.strip() for value in result.stdout.splitlines() if value.strip()]
    if len(ids) != 1:
        raise WebError("Expected exactly one running vbogs-vbgs-render container")
    return ids[0]


def _start_shared_viewer(run: dict[str, Any], gpu: str) -> None:
    run_root = Path(run["output_path"]) / run["scene_id"] / "local_viewer"
    model = run_root / "model"
    uncertainty = run_root / "uncertainty" / "U.npy"
    if not (model / "config.yaml").is_file() or not uncertainty.is_file():
        raise WebError("The completed run does not include a portable local viewer export")
    container = _render_container()
    # The run paths are generated by this service and scene ids are validated at
    # submission. No browser-provided command fragment is ever interpolated.
    command = "pkill -f 'scripts/view_octree_anygs.py' || true; exec " + shlex.join([
        "python", "scripts/view_octree_anygs.py", "--model-path", str(model), "--u-path", str(uncertainty), "--resolution", "4",
    ])
    subprocess.run(
        ["docker", "exec", "-d", "-w", "/workspace/VBOGS", "-e", f"CUDA_VISIBLE_DEVICES={gpu}", container, "sh", "-lc", command],
        check=True,
        capture_output=True,
        text=True,
    )


def create_app(*, root: Path | None = None, store_path: Path | None = None):
    from fastapi import FastAPI, Header, HTTPException
    from fastapi.responses import FileResponse, JSONResponse, StreamingResponse
    from fastapi.staticfiles import StaticFiles

    project_root = (root or repo_root()).resolve()
    data_root = Path(os.environ.get("VBOGS_GUI_DATA_ROOT", project_root / "data" / "gui")).resolve()
    output_root = Path(os.environ.get("VBOGS_GUI_OUTPUT_ROOT", project_root / "outputs" / "gui" / "runs")).resolve()
    db_path = store_path or data_root / "control.sqlite3"
    store = RunStore(db_path)
    presets = load_presets(project_root / "configs" / "gui" / "presets", project_root)
    scheduler = Scheduler(store, gpu_ids(), subprocess_runner)
    app = FastAPI(title="VBOGS Web Experiment Console")
    app.state.store = store
    app.state.scheduler = scheduler
    app.state.presets = presets
    app.state.project_root = project_root
    app.state.data_root = data_root
    app.state.output_root = output_root

    @app.middleware("http")
    async def proxy_identity(request, call_next):
        PROXY_USER.set(request.headers.get(os.environ.get("VBOGS_AUTH_USER_HEADER", "X-Forwarded-User")))
        return await call_next(request)

    static_dir = Path(os.environ.get("VBOGS_GUI_STATIC_DIR", project_root / "web" / "dist"))
    if static_dir.is_dir():
        app.mount("/assets", StaticFiles(directory=static_dir / "assets"), name="assets")

    @app.on_event("startup")
    async def startup() -> None:
        scheduler.start()

    @app.on_event("shutdown")
    async def shutdown() -> None:
        await scheduler.stop()

    def identity(x_forwarded_user: str | None = Header(default=None)) -> dict[str, Any]:
        user = PROXY_USER.get() or x_forwarded_user
        if not user:
            raise HTTPException(status_code=401, detail="Authenticated proxy identity is required")
        return {"user": user, "roles": sorted(roles_for(user))}

    def run_or_404(run_id: str) -> dict[str, Any]:
        run = store.get_run(run_id)
        if run is None:
            raise HTTPException(status_code=404, detail="Run not found")
        return run

    def authorize_owner(identity_value: dict[str, Any], run: dict[str, Any]) -> None:
        if "admin" not in identity_value["roles"] and run["owner"] != identity_value["user"]:
            raise HTTPException(status_code=403, detail="Only the owning operator or an admin may change this run")

    @app.get("/api/me")
    async def me(x_forwarded_user: str | None = Header(default=None)):
        return identity(x_forwarded_user)

    @app.get("/api/presets")
    async def get_presets(x_forwarded_user: str | None = Header(default=None)):
        identity(x_forwarded_user)
        return [preset.public() for preset in presets.values()]

    @app.get("/api/datasets")
    async def datasets(x_forwarded_user: str | None = Header(default=None)):
        identity(x_forwarded_user)
        clips = list_dataset_clips(dataset_name="all")
        return json.loads(clips_to_json(clips))

    @app.get("/api/slots")
    async def slots(x_forwarded_user: str | None = Header(default=None)):
        identity(x_forwarded_user)
        return scheduler.slots()

    @app.get("/api/runs")
    async def runs(x_forwarded_user: str | None = Header(default=None)):
        identity(x_forwarded_user)
        return store.list_runs()

    @app.post("/api/runs")
    async def create_run(request: Request, x_forwarded_user: str | None = Header(default=None)):
        principal = identity(x_forwarded_user)
        try:
            require_role(principal, "operator")
            payload = await request.json()
            if not isinstance(payload, dict):
                raise WebError("Expected a JSON object")
            dataset = str(payload["dataset"])
            scene_id = str(payload["scene_id"])
            preset_name = str(payload["preset"])
            start_at = str(payload.get("start_at", "prepare"))
            stop_after = str(payload.get("stop_after", "bundle"))
            if start_at not in STAGES or stop_after not in STAGES or STAGES.index(start_at) > STAGES.index(stop_after):
                raise WebError("Invalid pipeline stage slice")
            if not re.fullmatch(r"[A-Za-z0-9_.-]+", scene_id):
                raise WebError("Scene identifier contains unsupported characters")
            preset = presets.get(preset_name)
            if preset is None:
                raise WebError("Unknown preset")
            config = resolve_config(
                preset, repo_root=project_root, dataset=dataset, scene_id=scene_id,
                overrides=payload.get("overrides"), advanced_yaml=payload.get("advanced_yaml"),
            )
        except (KeyError, WebError, ConfigValidationError) as exc:
            raise HTTPException(status_code=422, detail=str(exc)) from exc
        run_id = f"run-{uuid.uuid4().hex[:12]}"
        workspace = data_root / "runs" / run_id
        output = output_root / run_id
        workspace.mkdir(parents=True, exist_ok=False)
        config_path = workspace / "resolved_config.yaml"
        config_path.write_text(yaml.safe_dump(config, sort_keys=True), encoding="utf-8")
        command = ["scripts/run_pipeline.sh", "--config", str(config_path), "--start-at", start_at, "--stop-after", stop_after]
        request_record = {"submitted_at": utc_now(), "submitted_by": principal["user"], "request": payload}
        (workspace / "request.json").write_text(json.dumps(request_record, indent=2, sort_keys=True) + "\n", encoding="utf-8")
        run = store.create_run({
            "id": run_id, "owner": principal["user"], "dataset": dataset, "scene_id": scene_id,
            "preset": preset_name, "start_at": start_at, "stop_after": stop_after, "created_at": utc_now(),
            "config_path": str(config_path), "workspace_path": str(workspace), "output_path": str(output), "command": command,
        })
        scheduler.notify()
        return JSONResponse(run, status_code=201)

    @app.get("/api/runs/{run_id}")
    async def run_detail(run_id: str, x_forwarded_user: str | None = Header(default=None)):
        identity(x_forwarded_user)
        run = run_or_404(run_id)
        return {**run, "manifest": _read_manifest(run), "events": store.events(run_id), "artifacts": _artifact_index(run)}

    @app.post("/api/runs/{run_id}/cancel")
    async def cancel(run_id: str, x_forwarded_user: str | None = Header(default=None)):
        principal = identity(x_forwarded_user)
        run = run_or_404(run_id)
        authorize_owner(principal, run)
        if run["status"] in TERMINAL_STATUSES:
            raise HTTPException(status_code=409, detail="Run is already terminal")
        await scheduler.cancel(run_id)
        return run_or_404(run_id)

    @app.post("/api/runs/{run_id}/resume")
    async def resume(run_id: str, request: Request, x_forwarded_user: str | None = Header(default=None)):
        principal = identity(x_forwarded_user)
        run = run_or_404(run_id)
        authorize_owner(principal, run)
        if run["status"] not in {"failed", "cancelled", "interrupted"}:
            raise HTTPException(status_code=409, detail="Only failed, cancelled, or interrupted runs may resume")
        payload = await request.json()
        start_at = str(payload.get("start_at", run["start_at"]))
        stop_after = str(payload.get("stop_after", run["stop_after"]))
        if start_at not in STAGES or stop_after not in STAGES or STAGES.index(start_at) > STAGES.index(stop_after):
            raise HTTPException(status_code=422, detail="Invalid pipeline stage slice")
        missing = [str(path) for path in stage_preconditions(run, start_at) if not path.exists()]
        if missing:
            raise HTTPException(status_code=422, detail={"message": "Missing resume artifacts", "paths": missing})
        cancel_file = Path(run["workspace_path"]) / "cancel.request"
        cancel_file.unlink(missing_ok=True)
        resumed = store.requeue(run_id, start_at=start_at, stop_after=stop_after)
        scheduler.notify()
        return resumed

    @app.get("/api/runs/{run_id}/events")
    async def run_events(run_id: str, after: int = 0, x_forwarded_user: str | None = Header(default=None)):
        identity(x_forwarded_user)
        run_or_404(run_id)
        return store.events(run_id, after)

    @app.get("/api/runs/{run_id}/events/stream")
    async def stream_events(run_id: str, x_forwarded_user: str | None = Header(default=None)):
        identity(x_forwarded_user)
        run = run_or_404(run_id)
        event_path = Path(run["workspace_path"]) / "pipeline.events.jsonl"
        async def stream() -> AsyncIterator[str]:
            sequence = 0
            byte_offset = 0
            while True:
                for event in store.events(run_id, sequence):
                    sequence = event["sequence"]
                    yield f"id: db-{sequence}\nevent: {event['type']}\ndata: {json.dumps(event)}\n\n"
                if event_path.exists():
                    with event_path.open("r", encoding="utf-8") as handle:
                        handle.seek(byte_offset)
                        for line in handle:
                            try:
                                event = json.loads(line)
                            except json.JSONDecodeError:
                                continue
                            yield f"event: pipeline\ndata: {json.dumps(event)}\n\n"
                        byte_offset = handle.tell()
                latest = store.get_run(run_id)
                if latest and latest["status"] in TERMINAL_STATUSES:
                    yield "event: terminal\ndata: {}\n\n"
                    return
                await asyncio.sleep(0.75)
        return StreamingResponse(stream(), media_type="text/event-stream", headers={"Cache-Control": "no-cache"})

    @app.get("/api/runs/{run_id}/log")
    async def log(run_id: str, tail: int = 200, x_forwarded_user: str | None = Header(default=None)):
        identity(x_forwarded_user)
        run = run_or_404(run_id)
        path = Path(run["workspace_path"]) / "pipeline.log"
        if not path.exists():
            return {"lines": []}
        lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
        return {"lines": lines[-max(1, min(tail, 5000)):]} 

    @app.get("/api/runs/{run_id}/artifacts/{artifact_path:path}")
    async def artifact(run_id: str, artifact_path: str, x_forwarded_user: str | None = Header(default=None)):
        identity(x_forwarded_user)
        run = run_or_404(run_id)
        root_path = (Path(run["output_path"]) / run["scene_id"]).resolve()
        candidate = (root_path / artifact_path).resolve()
        if root_path not in candidate.parents or not candidate.is_file():
            raise HTTPException(status_code=404, detail="Artifact not found")
        return FileResponse(candidate)

    @app.post("/api/compare")
    async def compare(request: Request, x_forwarded_user: str | None = Header(default=None)):
        identity(x_forwarded_user)
        payload = await request.json()
        ids = payload.get("run_ids") if isinstance(payload, dict) else None
        if not isinstance(ids, list) or len(ids) != 2 or ids[0] == ids[1]:
            raise HTTPException(status_code=422, detail="Select exactly two different run IDs")
        left, right = (run_or_404(str(run_id)) for run_id in ids)
        return {"runs": [{**run, "manifest": _read_manifest(run), "artifacts": _artifact_index(run)} for run in (left, right)]}

    @app.get("/api/viewer")
    async def viewer(x_forwarded_user: str | None = Header(default=None)):
        identity(x_forwarded_user)
        return store.viewer() or {"run_id": None}

    @app.post("/api/viewer")
    async def set_viewer(request: Request, x_forwarded_user: str | None = Header(default=None)):
        principal = identity(x_forwarded_user)
        try:
            require_role(principal, "admin")
            payload = await request.json()
            run = run_or_404(str(payload["run_id"]))
            gpu = str(payload["gpu_id"])
            if gpu not in scheduler.gpu_ids:
                raise WebError("Unknown GPU slot")
            if run["status"] != "completed":
                raise WebError("Only completed runs can be loaded in the shared viewer")
            if any(slot["gpu_id"] == gpu and slot["run_id"] for slot in scheduler.slots()):
                raise WebError("The selected GPU is occupied by a pipeline run")
        except (KeyError, WebError) as exc:
            raise HTTPException(status_code=422, detail=str(exc)) from exc
        try:
            _start_shared_viewer(run, gpu)
        except (OSError, subprocess.CalledProcessError, WebError) as exc:
            raise HTTPException(status_code=503, detail=f"Could not start shared viewer: {exc}") from exc
        store.set_viewer(run["id"], gpu, principal["user"])
        return {**(store.viewer() or {}), "url": os.environ.get("VBOGS_GUI_VIEWER_URL", "http://localhost:8071")}

    @app.get("/")
    async def index():
        index_path = static_dir / "index.html"
        if index_path.is_file():
            return FileResponse(index_path)
        return JSONResponse({"service": "vbogs-web", "detail": "Frontend assets were not built."})

    return app
